# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.3
loader_version=0.19.5
# Mod Properties
mod_version=1.9.8-26.3
maven_group=semmiedev
archives_base_name=disc_jockey
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_api_version=0.160.7+26.3
cloth_config_version=26.3.158
modmenu_version=21.0.0-beta.1